version: '3'

services:

  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: IDX
    ports:
      - "5444:5432"