CREATE SCHEMA IF NOT EXISTS stock;
create table IF NOT EXISTS stock.summary
(
    trade_date            date        not null,
    stock_code            varchar(10) not null,
    id_stock_summary      bigint,
    stock_name            text,
    remarks               text,
    previous              numeric,
    open_price            numeric,
    first_trade           numeric,
    high                  numeric,
    low                   numeric,
    close                 numeric,
    change                numeric,
    volume                bigint,
    value                 numeric,
    frequency             integer,
    index_individual      numeric,
    offer                 numeric,
    offer_volume          bigint,
    bid                   numeric,
    bid_volume            bigint,
    listed_shares         numeric,
    tradeable_shares      numeric,
    weight_for_index      numeric,
    foreign_sell          numeric,
    foreign_buy           numeric,
    delisting_date        date,
    non_regular_volume    bigint,
    non_regular_value     numeric,
    non_regular_frequency integer,
    persen                numeric,
    percentage            numeric,
    created_at            timestamp default now(),
    primary key (trade_date, stock_code)
);